# This is a Github Actions CI template file
name: PORTFOLIO WEB CI
on:
  push:
    branches:
      - deploy/dev

  workflow_dispatch:

env:
  REPO_ID: portfolio-web
  APP_NAME: portfolio_web

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:latest , ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:${{ steps.commit.outputs.short }}

  trigger-cd:
    needs: build-and-push-docker
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:latest
      - name: Run Docker Image via Docker Compose
        run: |
          cd ~/portfolio
          docker-compose up -d ${{ env.APP_NAME }}